export const escrowAbi = [
  "function createOrder(address seller, uint256 amount) returns (uint256 orderId)",
  "function markDelivered(uint256 orderId)",
  "function confirmDelivery(uint256 orderId)",
  "function claimAfterWindow(uint256 orderId)",
  "function refundBeforeDelivery(uint256 orderId)",
  "function raiseDispute(uint256 orderId)",
  "function requestRedemption(uint256 amount) returns (uint256 redemptionId)",
  "function confirmRedemption(uint256 redemptionId)",
  "function rejectRedemption(uint256 redemptionId)",
  "function resolveDispute(uint256 orderId, bool releaseToSeller)",
  "function setAutoReleaseWindow(uint256 newWindow)",
  "function setGovernance(address newGovernance)",
  "function acceptGovernance()",
  "function setOperator(address newOperator)",
  "function token() view returns (address)",
  "function autoReleaseWindow() view returns (uint256)",
  "function nextOrderId() view returns (uint256)",
  "function nextRedemptionId() view returns (uint256)",
  "function governance() view returns (address)",
  "function pendingGovernance() view returns (address)",
  "function operator() view returns (address)",
  "function orders(uint256) view returns (address buyer, address seller, uint256 amount, uint256 deliveredAt, uint8 status)",
  "function redemptions(uint256) view returns (address seller, uint256 amount, uint8 status)",
  "event OrderCreated(uint256 indexed orderId, address indexed buyer, address indexed seller, uint256 amount)",
  "event Delivered(uint256 indexed orderId)",
  "event Released(uint256 indexed orderId, address indexed to, uint256 amount)",
  "event Refunded(uint256 indexed orderId, address indexed to, uint256 amount)",
  "event Disputed(uint256 indexed orderId)",
  "event DisputeResolved(uint256 indexed orderId, bool releasedToSeller)",
  "event GovernanceTransferStarted(address indexed previousGovernance, address indexed pendingGovernance)",
  "event GovernanceTransferAccepted(address indexed previousGovernance, address indexed newGovernance)",
  "event OperatorUpdated(address indexed previousOperator, address indexed newOperator)",
  "event RedemptionRequested(uint256 indexed redemptionId, address indexed seller, uint256 amount)",
  "event RedemptionCompleted(uint256 indexed redemptionId, address indexed seller, uint256 amount)",
  "event RedemptionRejected(uint256 indexed redemptionId, address indexed seller, uint256 amount)",
  "error ZeroAddressError()",
  "error InvalidAmountError()",
  "error NotBuyerError()",
  "error NotSellerError()",
  "error NotPartyError()",
  "error WrongStatusError()",
  "error TransferFailedError()",
  "error OnlyGovernanceError()",
  "error OnlyPendingGovernanceError()",
  "error OnlyOperatorError()",
  "error CannotBuyOwnListingError()"
];
